### ISSUE TITLE
[Moderation] GPL Conformance

### ISSUE THREAD

**Issue by topjohnwu** [Magisk-Modules-Repo/nfsinjector#6]
We have noticed that while your module is licensed as GPL, no source code is provided.
Please comply to the license and release the source code within 7 days, or else we will have to remove your module.

Please do note that simply relicensing your current module with another license does not work, this is not how open source license works. Relicensing the module now does not remove the fact that you have released numerous versions of your module violating the license.

I will personally give you a pass and allow your module to still be online if you release the source code of your *current* release, you don't have to provide the whole history of your source code. But please do note that only doing so is *still* not perfectly legal in terms of GPL, this is simply my personal mercy.

**Comment by HafizZiq** [comment]
> We have noticed that while your module is licensed as GPL, no source code is provided.
> Please comply to the license and release the source code within 7 days, or else we will have to remove your module.
> 
> Please do note that simply relicensing your current module with another license does not work, this is not how open source license works. Relicensing the module now does not remove the fact that you have released numerous versions of your module violating the license.
> 
> I will personally give you a pass and allow your module to still be online if you release the source code of your _current_ release, you don't have to provide the whole history of your source code. But please do note that only doing so is _still_ not perfectly legal in terms of GPL, this is simply my personal mercy.

Oh ya thanks for this notice🙂ill remove the license since itsn an open source project (kanging problem)

**Comment by YaroST12** [comment]
Launching an attack on my kernel chat is not the wisest idea.
![IMG_20200212_120817_493](https://user-images.githubusercontent.com/26440429/74319750-8037ee80-4d90-11ea-9772-ab1cc809f9ad.jpg)

**Comment by HafizZiq** [comment]
> Launching an attack on my kernel chat is not the wisest idea.
> ![IMG_20200212_120817_493](https://user-images.githubusercontent.com/26440429/74319750-8037ee80-4d90-11ea-9772-ab1cc809f9ad.jpg)

That's not my job🤷🏻‍♂️

**Comment by YaroST12** [comment]
> > Launching an attack on my kernel chat is not the wisest idea.
> > ![IMG_20200212_120817_493](https://user-images.githubusercontent.com/26440429/74319750-8037ee80-4d90-11ea-9772-ab1cc809f9ad.jpg)
> 
> That's not my job🤷🏻‍♂️

That's your channel though.

**Comment by HafizZiq** [comment]
> > > Launching an attack on my kernel chat is not the wisest idea.
> > > ![IMG_20200212_120817_493](https://user-images.githubusercontent.com/26440429/74319750-8037ee80-4d90-11ea-9772-ab1cc809f9ad.jpg)
> > 
> > 
> > That's not my job🤷🏻‍♂️
> 
> That's your channel though.

Yes that's my channel but not my post and im at school rn
Discuss with dev in telegram
Im not in charge with this shit.

**Comment by YaroST12** [comment]
> > > > Launching an attack on my kernel chat is not the wisest idea.
> > > > ![IMG_20200212_120817_493](https://user-images.githubusercontent.com/26440429/74319750-8037ee80-4d90-11ea-9772-ab1cc809f9ad.jpg)
> > > 
> > > 
> > > That's not my job🤷🏻‍♂️
> > 
> > 
> > That's your channel though.
> 
> Yes that's my channel but not my post and im at school rn
> Discuss with dev in telegram
> Im not in charge with this shit.
> Thank you

You are in school, able to chat on GitHub, yet unable to take down a post from your own channel. Understandable, have a nice day.

**Comment by HafizZiq** [comment]
> > > > > Launching an attack on my kernel chat is not the wisest idea.
> > > > > ![IMG_20200212_120817_493](https://user-images.githubusercontent.com/26440429/74319750-8037ee80-4d90-11ea-9772-ab1cc809f9ad.jpg)
> > > > 
> > > > 
> > > > That's not my job🤷🏻‍♂️
> > > 
> > > 
> > > That's your channel though.
> > 
> > 
> > Yes that's my channel but not my post and im at school rn
> > Discuss with dev in telegram
> > Im not in charge with this shit.
> > Thank you
> 
> You are in school, able to chat on GitHub, yet unable to take down a post from your own channel. Understandable, have a nice day.

Let me repeat once again.
![Screenshot_20200212-173449](https://user-images.githubusercontent.com/46204743/74321971-21896980-4dbe-11ea-85ec-37d310605f0f.jpg)

**Comment by Didgeridoohan** [comment]
> Oh ya thanks for this notice🙂ill remove the license since itsn an open source project (kanging problem)
> Thanks.

Note that it is not enough to just remove the license (as @topjohnwu wrote). The current module has already been released under GPLv3 and as such you need to release the source code for that.

**Comment by TjReiny** [comment]
this can be reverted as the Dev wish.

**Comment by YaroST12** [comment]
> this can be reverted as the Dev wish.(release an total cutdown version, make sure there are no else versions on ur github tho. apply GPL once(release sourcecode) and then shutdown Licensing) next version dont have to follow GPL at all.(make sure u dont put any sourcecode on github. it Forces ya to use GPL). Profit.

...or how to get your module deleted from Magisk-Modules-Repo.

**Comment by HafizZiq** [comment]
If so then ill do last release with GPL.

**Comment by HafizZiq** [comment]
@topjohnwu 
Here ur needs
https://github.com/HafizZiq/nfs

Peace out

**Comment by YaroST12** [comment]
Nice. Now remove this from your tweaker TG channel so I can reopen my chat.
![Screenshot_Telegram_20200212-120749](https://user-images.githubusercontent.com/26440429/74435058-a8991900-4e74-11ea-98bf-85e33b4d103b.png)

**Comment by YaroST12** [comment]
Now remove this from your tweaker's TG channel so I can reopen again.
![IMG_20200212_120817_493](https://user-images.githubusercontent.com/26440429/74435119-cbc3c880-4e74-11ea-95ad-d8e127d7b64c.jpg)

**Comment by HafizZiq** [comment]
> Now remove this from your tweaker's TG channel so I can reopen my chat again.
> ![IMG_20200212_120817_493](https://user-images.githubusercontent.com/26440429/74435119-cbc3c880-4e74-11ea-95ad-d8e127d7b64c.jpg)

N then unblock nfs from any blocker
We dont have any history that brick any devices since the first launch.

**Comment by YaroST12** [comment]
> If nfs still in ur blocker list, we will never drop the statement.

I don't have control over every kernel that picked tweaker blocker. That's absurd.

**Comment by HafizZiq** [comment]
> > If nfs still in ur blocker list, we will never drop the statement.
> 
> I don't have control over every kernel that picked tweaker blocker. That's absurd.

U are the one who started this blocker..

**Comment by nysascape** [comment]
> > > If nfs still in ur blocker list, we will never drop the statement.
> > 
> > 
> > I don't have control over every kernel that picked tweaker blocker. That's absurd.
> 
> U are the one who started this blocker..

Actually I'll think you'll find the concept of blockers has been around for a while. See https://github.com/nysascape/kernel_xiaomi_acrux/commit/b8782e37627b61eab8d3190a1c88fe0d436ed969

@YaroST12 here just happened to make a blocker that got rid of modules. He doesn't target you - same way as in that blocker I'm not targeting any app, it's the kernel developer on the other end that decides what's blocked and what's not. If your tweaker has had a history of bricking others devices, we have nothing but concern for our users flashing these modules on our devices as an individual blacklist is more than enough.

I'm going to ask again that you remove the post in your channel targeting Yaro here, you have FULL control over your own Telegram channel, just delete it, stop being butthurt because one kernel developer didn't trust your work, and move on. You've still got thousands using your module.

**Comment by HafizZiq** [comment]
> If users wanted it so badly they'd just revert the commit and rebuild.
And how if i revert to you back;
> If you and yaro want the post down so badly, revert the commit or at least remove nfs from blocker list, rebuild, and stop talking shit about our modules.
Deal?

**Comment by HafizZiq** [comment]
> If users wanted it so badly they'd just revert the commit and rebuild.

And how if i revert to you back;
> If you and yaro want the post down so badly, revert the commit or at least remove nfs from blocker list, rebuild, and stop talking shit about our modules.

Deal?

**Comment by nysascape** [comment]
> > If users wanted it so badly they'd just revert the commit and rebuild.
> > And how if i revert to you back;
> > If you and yaro want the post down so badly, revert the commit or at least remove nfs from blocker list, rebuild, and stop talking shit about our modules.
> > Deal?

No, because if you have a history of bricking our devices, we are going to block your module as to avoid our and somewhat your pain of being slammed about NFS bricking phones.

If you stopped bricking certain phones, and tweaking things that are useless and things that should be left to the kernel developer, like FDE and others also do, then we would probably remove these modules from the list. Your "optimizer" messes with tunables and things that we want to tweak and leave it there, and like I said, certain UFS tweaks and others actually end up bricking devices.

I don't even have the blocker picked because I haven't updated Acrux for a while due to a break from stuff, but I'll be sure to pick it and you can send all the spam you want, but until we see an actual use from these modules and not malicious/useless behaviour that just simply gets our userbases moaning at us, NFS and all the other modules doing the same will probably stay blocked.

We have every right in the interest of our users. You violated GPL, made a useless, dangerous tweaker and then when we block you, you send us spam instead of just learning to take criticism. Why do you even care if we're blocking your module, if it's so brilliant, developers that make kernels wouldn't block it. 

It just sounds like you're truly butthurt because we block your module. Get over yourself.

**Comment by HafizZiq** [comment]
> No, because if you have a history of bricking our devices, we are going to block your module as to avoid our and somewhat your pain of being slammed about NFS bricking phones.

Prove all about NFS bricking device, anything possible

> and like I said, certain UFS tweaks and others actually end up bricking devices.

And again, we dont tweak UFS like FDE do.
Source are open in my repository, and if nfs do so, point it to me.

> NFS will probably stay blocked.

Kthx

> You violated GPL

Source are open now, what i violated more?


> made a useless, dangerous tweaker

We do? And what our purposes to take different user with different phone to be in our testing team?
We're test beta/alpha build heavily before releasing clean stable

> Why do you even care if we're blocking your module

Why do you even care if we're made that post

> It just sounds like you're truly butthurt because we block your module. Get over yourself.

Luckily im not alone, you're also truly but(t)hurt because of our post.

**Comment by YaroST12** [comment]
> Source are open now, what i violated more?

**NOW**
They must be open since day 1 if you are using GPL-v3 licence.



> Luckily im not alone

You will not believe how alone you are.

**Comment by HafizZiq** [comment]
> > Source are open now, what i violated more?
> 
> **NOW**
> They must be open since day 1 if you are using GPL-v3 licence.
> 
> > Luckily im not alone
> 
> You will not believe how alone you are.

Kthx
